# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dr2Dt7UOz93WK0YWcovb32vD0N3sOKwG
"""



import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
df=pd.read_csv('wo_men1.csv')
print(df.head())
df.dropna(inplace=True)
df=np.array(df)
x=df[:,2:]
y=df[:,1]
clf=KNeighborsClassifier()
clf.fit(x,y)
height=int(input("enter the height= "))
shoe=int(input("enter the shoe size="))

accuracy=clf.score(x,y)
print("the accuracy of this prediction=",accuracy)
prediction=clf.predict([[height,shoe]])
print("your gender is = ",prediction)